# Generated by Django 4.1.5 on 2023-03-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pediatric_clinic', '0005_alter_booking_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='polio_vaccine',
            field=models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Pending', 'Pending'), ('Non-Vaccinated', 'Non-Vaccinated')], default='Pending', max_length=20),
        ),
    ]
