# Generated by Django 4.1.5 on 2023-03-09 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pediatric_clinic', '0006_alter_patient_polio_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='polio_vaccine',
            field=models.CharField(choices=[('Vaccinated', 'Vaccinated'), ('Pending', 'Pending'), ('Not Vaccinated', 'Not Vaccinated')], default='Pending', max_length=20),
        ),
    ]
