# Generated by Django 4.1.5 on 2023-03-09 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pediatric_clinic', '0007_alter_patient_polio_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='polio_vaccine',
            field=models.CharField(max_length=255),
        ),
    ]
