# Generated by Django 4.1.5 on 2023-03-10 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pediatric_clinic', '0008_alter_patient_polio_vaccine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthdate',
            field=models.DateField(null=True),
        ),
    ]
